name: Build and Push Docker Image to Docker Hub

# Run when code is merged to main (push to main)
on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: cicd-d4-t1-build-and-push
    runs-on: ubuntu-latest   # <-- GitHub-hosted runner
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up QEMU (optional for multiplatform)
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Prepare tags
        run: |
          echo "SHORT_SHA=$(echo ${GITHUB_SHA} | cut -c1-7)" >> $GITHUB_ENV
          echo "IMAGE_NAME=${{ secrets.DOCKERHUB_REPO }}" >> $GITHUB_ENV
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./task1
          file: ./task1/Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ env.SHORT_SHA }}


      - name: Output pushed image
        run: |
          echo "Pushed images:"
          echo "${{ env.IMAGE_NAME }}:latest"
          echo "${{ env.IMAGE_NAME }}:${{ env.SHORT_SHA }}"
